#compile match split sub
import re
pattern=re.compile(r'hello')
match=pattern.match("hello world")
m=re.match(r"hell",'hellworld')
n=re.match(r"world$","hellworld")
p=re.compile(r'\d+')
r=p.split("one1two2three3four4")
f=p.findall("one1two2three3four4")
l=re.search(r'he','worhell')
print(l)
p2=re.compile(r'[abc]')
k=p2.sub('O','Markmarkmarkmark',count=2)
print(k)
print(f)
print(r)
print(n)
print(m.group())
print(match.group())
